name: What's Due Today?

on:
  workflow_dispatch:
  schedule:
    - cron: '6 5 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Check CISA KEV for Vulns Due Today
      run: curl --silent https://www.cisa.gov/sites/default/files/csv/known_exploited_vulnerabilities.csv | grep -e "Apply updates per vendor instructions.,""$(date -I)" -e "cveID,vendorProject" > vulns-due/$(date -I)-cisa-kev-due.csv

    - name: Clean scrape if only contains header
      run: find vulns-due/ -size 97c |  xargs rm
      
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Update data: ${timestamp}" || exit 0
        git push