name: What's Added Today?

on:
  workflow_dispatch:
  schedule:
    - cron: '6 3,11,23 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Scrape Entire CISA KEV to latest File
      run: curl --silent --output cisa-kev-latest.json https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json

    - name: Scrape CISA KEV For Updates Only
      run: curl -s 'https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json' | jq -r --arg d "$(date -I)" '.vulnerabilities[] |  select(.dateAdded==$d)' > vulns-added/$d-cisa-kev-new.json

    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Update data: ${timestamp}" || exit 0
        git push
