name: What's Added Today?

on:
  workflow_dispatch:
  schedule:
    - cron: '6 18 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Scrape Entire CISA KEV to latest File
      run: curl --silent --output cisa-kev-latest.csv https://www.cisa.gov/sites/default/files/csv/known_exploited_vulnerabilities.csv

    - name: Scrape CISA KEV For Updates Only
      run: curl --silent https://www.cisa.gov/sites/default/files/csv/known_exploited_vulnerabilities.csv | grep -e $(date -I), -e "cveID,vendorProject" > vulns-added/$(date -I)-cisa-kev-new.csv

    - name: Clean scrape if only contains header
      run: find vulns-added/ -size 97c |  xargs rm

    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Update data: ${timestamp}" || exit 0
        git push